DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 30
  NUM_WORKERS: 8

OPTIM:
  NAME: "sgd"
  LR: 0.0035
  MAX_EPOCH: 5
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

MODEL:
  BACKBONE:
    NAME: "ViT-B/32"

THRESHOLDS: [25.8, 23.41, 27.01, 26.0, 28.45]
    